spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_security
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 655368566D597133743677397A24432646294A404E635266556A576E5A723475
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days