spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.b60220ccb5db4ac1
            client-secret: b41f236ea62f729fdcf8313dcaf3462877240c13
          google:
            client-id: 144795826088-0vnc34kp2ujaon56l0e00il7ul4187ue.apps.googleusercontent.com
            client-secret: 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
